spring:
  cloud:
    openfeign:
      client:
        config:
          nbrb-service:
            url: https://api.nbrb.by/exrates/currencies
#            url:  https://api.nbrb.by/exrates/currencies/456