spring:
  cloud:
    openfeign:
      client:
        config:
          nbrb-service:
            url: https://api.nbrb.by/exrates/rates

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:vadarod
    username: admin
    password: admin
    driverClassName: org.h2.Driver
