spring:
  application:
    name: vadarod

  profiles:
    active: dev

  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:vadarod
    username: admin
    password: admin
    driverClassName: org.h2.Driver

request:
  value:
    periodicity: 0
    parammode: 2